sudo: required
dist: trusty
group: edge

# whitelist
branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true


language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++

    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libiomp-dev
      env:
        - COMPILER=clang++
        - CXXFLAGS="-fopenmp=libiomp5"

before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive autotools-dev libicu-dev libxml2-dev libbz2-dev zlib1g-dev libboost-dev libboost-regex-dev libtar-dev
    - git clone https://github.com/proycon/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
install:
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make CXX=$COMPILER check
