sudo: required
dist: trusty
group: edge

# whitelist
branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true


language: cpp

matrix:
  include:
    - os: linux
      compiler: g++

    - os: linux
      compiler: clang++
      env:
        - OPENMPFLAG=--disable-openmp

before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive autotools-dev libicu-dev libxml2-dev libbz2-dev zlib1g-dev libboost-dev libboost-regex-dev libtar-dev
    - git clone https://github.com/proycon/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure $OPENMPFLAG
    - make
    - sudo make install
    - cd ..
install:
    - bash bootstrap.sh
    - ./configure $OPENMPFLAG
    - make
    - sudo make install
script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make check
