.TH TICCL-LDcalc 1 "2016 jul 05"

.SH NAME
TICCL-LDcalc - calculate stuff

.SH SYNOPSYS

TICCL-LDcalc [options]

.SH DESCRIPTION
.B TICCL-LDcalc
read a confusion list file and creates an inputfile for TICCL-rank

.SH OPTIONS

.B --index
conflist
.RS
name of the confusion list file produced by
.B TICCL-indexer
or
.B TICCL-indexerNT
.RE

.B --hash
anahash
.RS
name of the anagram hasegs file produced by
.B TICCL-anahash
.RE

.B --alph
alphabet
.RS
name of the an alphabet file generated with
.B TICCL-lexstat
.RE

.B --clean
clean
.RS
name of the 'clean' file as produced by
.B TICCL-unk
.RE

.B --hist
hist
.RS
name of the 'historical confusions' file
.RE

.B --nohld
.RS
ignore
.B --LD
for 'historical' confusionns

.RE

.B --diac
diacritics
.RS
a list of 'diacritical' confusions
.RE

.B -o
outfile
.RS
store the results is 'outfile'
.RE

.B --LD
distance
.RS
calculate results upto an edit distance of 'distance'
.RE

.B --artifrq
artifreq
.RS
decrease all frequencies with value 'artifreq'
.RE

.B -t
threads
.RS
run on 'threads' parallel.
.RE

.B -v
.RS
be (very) verbose.
.RE

.B -V
.RS
show version
.RE


.SH BUGS
possibly

.SH AUTHORS
Ko van der Sloot Timbl@uvt.nl

Martin Reynaert reynaert@uvt.nl
